[Settings]
# Added automatically by the Netlify CLI. It has no effect during normal 
# Git-backed deploys.
ID = "a7370f85-58d1-439a-abfe-730093565f4f"



[build]

  base = "/"

  publish = "/"

 
  command = "echo 'default context'"

 
[context.production]
  publish = "/"
  command = "make publish"




[[headers]]
  for = "/*"
  [headers.values]
  
  /*
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Powered-By: Mudah
Strict-Transport-Security:max-age=10800; includeSubDomains, preload;
Content-Security-Policy: default-src 'self'  *.susetyo.web.id *.disqus.com *.github.com *.wikipedia.com; base-uri 'self'; 
Content-Security-Policy: frame-ancestors 'none';script-src 'self' *.susetyo.web.id *.disqus.com www.google-analytics.com ajax.googleapis.com;style-src 'self';
Content-Security-Policy: report-uri https://sentry.io/api/1356512/security/?sentry_key=babc3d23ddab4967b27c87cfb7438470
Referrer-Policy: no-referrer
Server: Nusa
ServerSignature: off
Feature-Policy: geolocation self
