[Settings]
# Added automatically by the Netlify CLI. It has no effect during normal 
# Git-backed deploys.
ID = "a7370f85-58d1-439a-abfe-730093565f4f"

[[headers]]
  for = "/*"
  [headers.values]

Cache-Control = "public, max-age=31536000"
Access-Control-Allow-Origin = "*"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"

Strict-Transport-Security = "max-age=31536000; includeSubDomains;preload;"
Content-Security-Policy = "default-src 'none';frame-ancestors 'none';base-uri 'self'; child-src 'none'; connect-src https://susetyo.web.id; form-action 'self'; frame-src 'none'; img-src   https://susetyo.web.id https://*.wikimedia.org https://*.blogspot.com; manifest-src 'none'; media-src 'none'; object-src 'none'; script-src   https://susetyo.web.id ; style-src 'self' https://susetyo.web.id; worker-src 'none'; font-src https://susetyo.web.id; prefetch-src https://susetyo.web.id"
 
ServerTokens = "Prod"
ServerSignature = "Off"
FileETag = "None"
TraceEnable = "Off"


Referrer-Policy = "strict-origin-when-cross-origin"
 
Feature-Policy = "geolocation self"

 



 
 




