[Settings]
# Added automatically by the Netlify CLI. It has no effect during normal 
# Git-backed deploys.
ID = "a7370f85-58d1-439a-abfe-730093565f4f"

[[headers]]
  for = "/*"
  [headers.values]

Cache-Control = "public, max-age=360000"
Access-Control-Allow-Origin = "*"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"

Strict-Transport-Security = "max-age=21600; includeSubDomains, preload;"

Content-Security-Policy = "default-src 'none';frame-ancestors 'none';script-src  *.susetyo.web.id *.disqus.com *.google-analytics.com *.googleapis.com;style-src https: 'unsafe-inline';"


Referrer-Policy = "strict-origin-when-cross-origin"
 
Feature-Policy = "geolocation self"





 
 




